routes/web.php
<?php

use App\Http\Controllers\CategorieController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [App\Http\Controllers\Controller::class, 'index'])->name('home');
Auth::routes();
Route::resource('posts',PostController::class)->middleware('auth');
Route::resource('categories',CategorieController::class);
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::delete('post/force/{id}', [PostController::class, 'forceDestroy'])->name('post.force.destroy');
Route::put('post/restore/{id}', [PostController::class, 'restore'])->name('post.restore');
Route::delete('categories/force/{id}', [CategorieController::class, 'forceDestroy'])->name('categories.force.destroy');
Route::put('categories/restore/{id}', [CategorieController::class, 'restore'])->name('categories.restore');
Route::delete('category/delete/{id}', [CategorieController::class, 'delete'])->name('category.delete');
Route::get('/showall/{slug}', [Controller::class,'index']);
Route::get('/show/post/{id}', [PostController::class,'showp'])->name('showp');
Route::post('/showall/recherche', [PostController::class,'recherche'])->name('recherche');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use HasFactory,SoftDeletes;
    Protected $fillable =['title','description','image','user_id'] ;

    public function user()
    {

        return $this->belongsTo(User::class);


    }

    public function category()
    {
        return $this->belongsToMany(Category::class);
    }

}

app/Http/Controllers/Api/PostController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return Post::all();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Post::create($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return $post;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $post->update($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($slug =null)
    {
        $post= Post::withTrashed()->oldest('title')->paginate(5);
        return view ('posts/index',compact('post'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = Category::all();
        return view('/posts/create',compact('category'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        $post = new Post();
        $post->title = $input['title'];
        $post->description = $input['description'];
        $input["user_id"] = \Auth::user()->id;
        $post->user_id =   $input["user_id"];

        if (isset($input['image'])) {
            $post->image = $this->upload($input['image']);

        }
        $post->save();

        $post->category()->attach($input['categpost']);
        return redirect()->route('posts.index')->with('info', 'Le item a bien été créer ');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('posts/show',compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {

        $categ = Category::all();
        return view('posts/edit', compact('post','categ'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
        $post = Post::where('id',$id)->first();
        $im = $post->image;
        $post->title = $input['title'];
        $post->description = $input['description'];
        $input["user_id"] = \Auth::user()->id;
        $post->user_id =   $input["user_id"];

        if (isset($input['image'])){
            $post->image =  $this->upload($input['image']) ;

        }
        else { $post->image =$im;}
        $post->update();

        $post->category()->sync($input['categpost']);

        return redirect()->route('posts.index')->with('info', 'Le item a bien été créer ');
    }


    public function upload ($file){
        $extension = $file->getClientOriginalExtension();
        $sha1 = sha1($file->getClientOriginalName());
        $filename = date('Y-m-d-h-i-s').$sha1.".".$extension ;
        $path = public_path('images/');
        $file->move($path,$filename);
        return $filename ;

    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Post::findOrfail($id)->delete();
        return back()->with('info', 'Le film a bien été mis dans la corbeille.');
    }

    public function restore($id)
    {
        Post::withTrashed()->whereId($id)->firstOrFail()->restore();
        return back()->with('info', 'Le film a bien été restauré.');
    }

    public function forceDestroy($id)
    {
        Post::withTrashed()->whereId($id)->firstOrFail()->forceDelete();
        return back()->with('info', 'Le film a bien été supprimé définitivement dans
la base de données.');
    }

public function showp($id){

  $post = Post::where('id',$id)->first();
    return view('posts/show',compact('post'));
}

public function recherche(Request $request,$slug= null){
    $cat = Category::all();
    $input = $request->all();
    $post=  Post::where('title','like','%' . $input['post'] . '%')->paginate(5);
    return view('home2',compact('post','cat','slug'));
}

}

resources/views/posts/create.blade.php
@extends('welcome')

@section('content')
    <h1>Create Post</h1>

    <form  method="post" action="{{ route('posts.store') }}" enctype="multipart/form-data">
        @csrf
        <div id="items">
            <div class="form-group"><label for="items_title" class="required">Title</label><input type="text" id="title" name="title" required="required" maxlength="255" class="form-control" value=""></div>
            <div class="form-group"><label for="items_description" class="required">Description</label><input type="text" id="items_description" name="description" required="required" maxlength="255" class="form-control" value=""></div>
            <div class="form-group">
                <label for="items_image">Image</label>
                <div class="custom-file"><input type="file" id="items_image" name="image" lang="en" class="custom-file-input"><label for="items_image" class="custom-file-label"></label>
                </div>
            </div>

            <div class="form-group">


                <label class="" for="items_menu">Menu</label>

                <select id="categpost" name="categpost" class="form-control">
                    @foreach( $category as $cat)

                        <option  value="{{$cat->id}}"  >{{ $cat->title }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <button class="btn btn-outline-primary" style="    margin: -21px;
      margin-top: 34px;">Update</button>
    </form>

    <a href="{{ route('posts.index') }}" Class="btn btn-outline-secondary" style="    margin-top: -21px;
    margin-left: 115px;">back to list</a>

    {{--{{ include('items/_delete_form.html.twig') }}--}}
@endsection

resources/views/posts/edit.blade.php
@extends('welcome')

@section('content')
<h1>Edit Post</h1>

<form  method="post" action="{{ route('posts.update',$post->id) }}" enctype="multipart/form-data">
    @csrf
    @method('put')
    <div>
        <div class="form-group"><label for="items_title" class="required">Title</label><input type="text" id="title" name="title" required="required" maxlength="255" class="form-control" value="{{ $post->title }}"></div>
        <div class="form-group"><label for="items_description" class="required">Description</label><input type="text" id="items_description" name="description" required="required" maxlength="255" class="form-control" value="{{ $post->description }}"></div>
        <div class="form-group">
            <label for="items_image">Image</label>
            <div class="custom-file"><input type="file" id="items_image" name="image" lang="en" class="custom-file-input"><label for="items_image" class="custom-file-label"></label>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="" for="items_menu">Menu</label>

        <select id="items_menu" name="categpost[]" class="form-control" multiple>
            @foreach( $categ as $cat)

                <option   value="{{ $cat->id }}"  >{{ $cat->title }}</option>
            @endforeach
        </select>
    </div>
    <button class="btn btn-outline-primary" style="    margin: -21px;
      margin-top: 34px;">Update</button>
</form>

<a href="{{ route('posts.index') }}" Class="btn btn-outline-secondary" style="    margin-top: -21px;
    margin-left: 115px;">back to list</a>

{{--{{ include('items/_delete_form.html.twig') }}--}}
@endsection

resources/views/posts/index.blade.php
@extends('welcome')

@section('content')
    <h1 style="font-family:'Dancing Script', cursive  !important;font-size: 67px;
    text-align: center; "class=" animate__animated animate__backInLeft">Posts Liste</h1>

    <a href="{{ route('posts.create') }}" class="btn btn-outline-dark" style="float: right;margin-bottom: 22px;">Create Post</a>
    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Image</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($post as  $posts )
            <tr>


                <td>{{ $posts->title }}</td>
                <td>{{ $posts->Description }}</td>
                <td><img src="/images/{{ $posts->image}}" height="100px"></td>

                {{--                                <td>{{ menu.createdAt ? menu.createdAt|date('Y-m-d H:i:s') : '' }}</td>--}}
                {{--                                <td>{{ menu.updateAt ? menu.updateAt|date('Y-m-d H:i:s') : '' }}</td>--}}
                <td>
                    <a href="{{ route('posts.show',$posts->id) }}" class="btn btn-outline-primary" style="width: 80px">show</a>
                    <a href="{{ route('posts.edit',$posts->id) }}" class="btn btn-outline-warning" style="width:80px;">edit</a>
                    @if($posts->deleted_at)
                        <form action="{{ route('post.restore',$posts->id) }}"

                              method="post">

                            @csrf
                            @method('PUT')
                            <button style="margin-left: 170px;margin-top: -67px;" class="btn btn-outline-success"

                                    type="submit">Restaurer</button>
                        </form>


                        <form action="{{ route('post.force.destroy',$posts->id) }}"
                              method="post">
                            @csrf
                            @method('DELETE')

                            <button
                                class="btn btn-outline-danger" style="width:200px;margin-top: -114px;margin-left: 267px"
                                type="submit">Supprimer definitivement</button>
                        </form>


                        @else
                        <form action="{{ route('posts.destroy',$posts->id) }}"
                              method="post">
                            @csrf
                            @method('DELETE')

                            <button
                                class="btn btn-outline-danger" style="width:100px;margin-top: -67px;margin-left:170px"
                                type="submit">Supprimer</button>
                        </form>
                @endif
            </tr>
        @endforeach

        </tbody>

    </table>
    <div class="navigation">
        {{ $post->links() }}
    </div>


@endsection

resources/views/posts/show.blade.php
@extends('welcome')

@section('content')



<div class="row">
    <div class="col-md-5">
        <img src="/images/{{ $post->image }}" alt="{{ $post->title }}" class="img-fluid">
    </div>
    <div class="col-md-7 my-auto">
        <h3>{{ $post->title }}</h3>
        <p>{{ $post->description }}</p>
        <h4>Categories :</h4>
       @foreach(  $post->category as $ca)

        <h6>{{ $ca->title }}</h6>
        @endforeach
        <h4>Created By :</h4>
        {{$post->user->name }}
        <hr>
        <p>

        </p>
    </div>
</div>
<hr>
@auth()
<div style="text-align: center">
    <a href="{{ route('posts.index') }}"class="btn btn-outline-primary" style="">back to list</a>

    <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-outline-warning" style="">edit</a>

{{--    {{ include('items/_delete_form.html.twig') }}--}}
</div>
@endauth


@endsection