routes/web.php
<?php

use App\Http\Controllers\CategorieController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [App\Http\Controllers\Controller::class, 'index'])->name('home');
Auth::routes();
Route::resource('posts',PostController::class)->middleware('auth');
Route::resource('categories',CategorieController::class);
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::delete('post/force/{id}', [PostController::class, 'forceDestroy'])->name('post.force.destroy');
Route::put('post/restore/{id}', [PostController::class, 'restore'])->name('post.restore');
Route::delete('categories/force/{id}', [CategorieController::class, 'forceDestroy'])->name('categories.force.destroy');
Route::put('categories/restore/{id}', [CategorieController::class, 'restore'])->name('categories.restore');
Route::delete('category/delete/{id}', [CategorieController::class, 'delete'])->name('category.delete');
Route::get('/showall/{slug}', [Controller::class,'index']);
Route::get('/show/post/{id}', [PostController::class,'showp'])->name('showp');
Route::post('/showall/recherche', [PostController::class,'recherche'])->name('recherche');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    Protected $fillable =['title','description'] ;
    use HasFactory,SoftDeletes;

    public function post()
    {
        return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/Api/CategoryController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return Category::all();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Category::create($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
      return $category;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $category->update($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
    }
}

resources/views/category/create.blade.php
@extends('welcome')

@section('content')
    <h1>Create Post</h1>

    <form  method="post" action="{{ route('categories.store') }}" enctype="multipart/form-data">
        @csrf
        <div id="items">
            <div class="form-group"><label for="items_title" class="required">Title</label><input type="text" id="name" name="name" required="required" maxlength="255" class="form-control" value=""></div>
            <div class="form-group"><label for="items_description" class="required">Description</label><input type="text" id="slug" name="slug" required="required" maxlength="255" class="form-control" value=""></div>



        </div>
        <button class="btn btn-outline-primary" style="    margin: -21px;
      margin-top: 34px;">Update</button>
    </form>

    <a href="{{ route('categories.index') }}" Class="btn btn-outline-secondary" style="    margin-top: -21px;
    margin-left: 115px;">back to list</a>

    {{--{{ include('items/_delete_form.html.twig') }}--}}
@endsection

resources/views/category/edit.blade.php
@extends('welcome')

@section('content')
<h1>Edit Categorie</h1>

<form  method="post" action="{{ route('categories.update',$category->id) }}" enctype="multipart/form-data">
    @csrf
    @method('put')
    <div id="items">
        <div class="form-group"><label for="items_title" class="required">Title</label><input type="text" id="title" name="title" required="required" maxlength="255" class="form-control" value="{{ $category->title }}"></div>
        <div class="form-group"><label for="items_description" class="required">Description</label><input type="text" id="items_description" name="slug" required="required" maxlength="255" class="form-control" value="{{ $category->slug }}"></div>

    </div>
    <button class="btn btn-outline-primary" style="    margin: -21px;
      margin-top: 34px;">Update</button>
</form>

<a href="{{ route('categories.index') }}" Class="btn btn-outline-secondary" style="    margin-top: -21px;
    margin-left: 115px;">back to list</a>

{{--{{ include('items/_delete_form.html.twig') }}--}}
@endsection

resources/views/category/index.blade.php
@extends('welcome')

@section('content')
    <h1 style="font-family:'Dancing Script', cursive  !important;font-size: 67px;
    text-align: center; ">Categories Liste</h1>

    <a href="{{ route('categories.create') }}" class="btn btn-outline-dark" style="float: right;margin-bottom: 22px;">Create Category</a>
    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
        </tr>
        </thead>
{{--        <tbody>--}}
{{--        @foreach($category as $cat)--}}
{{--            <tr>--}}


{{--                <td>{{ $cat->title  }}</td>--}}
{{--                <td>{{ $cat->slug  }}</td>--}}



{{--                    <a href="{{ route('categories.show',$cat->id) }}" class="btn btn-outline-primary" style="width: 80px">show</a>--}}
{{--                    <a href="{{ route('categories.edit',$cat->id) }}" class="btn btn-outline-warning" style="width:80px;">edit</a>--}}
{{--                    @if($cat->deleted_at)--}}
{{--                        <form action="{{ route('categories.restore',$cat->id) }}"--}}

{{--                              method="post">--}}

{{--                            @csrf--}}
{{--                            @method('PUT')--}}
{{--                            <button style="margin-left: 170px;margin-top: -67px;" class="btn btn-outline-success"--}}

{{--                                    type="submit">Restaurer</button>--}}
{{--                        </form>--}}


{{--                        <form action="{{ route('categories.force.destroy',$cat->id) }}"--}}
{{--                              method="post">--}}
{{--                            @csrf--}}
{{--                            @method('DELETE')--}}

{{--                            <button--}}
{{--                                class="btn btn-outline-danger" style="width:200px;margin-top: -114px;margin-left: 267px"--}}
{{--                                type="submit">Supprimer definitivement</button>--}}
{{--                        </form>--}}


{{--                    @else--}}
{{--                        <form action="{{ route('category.delete',$cat->id) }}"--}}
{{--                              method="post">--}}
{{--                            @csrf--}}
{{--                            @method('DELETE')--}}

{{--                            <button--}}
{{--                                class="btn btn-outline-danger" style="width:100px;margin-top: -67px;margin-left:170px"--}}
{{--                                type="submit">Supprimer</button>--}}
{{--                        </form>--}}
{{--                @endif--}}
{{--            </tr>--}}
{{--        @endforeach--}}
{{--        </tbody>--}}


        <tbody>
        @foreach($category as $cat)
            <tr>


                <td>{{ $cat->title  }}</td>
                <td>{{ $cat->description }}</td>
                {{--                                <td>{{ menu.createdAt ? menu.createdAt|date('Y-m-d H:i:s') : '' }}</td>--}}
                {{--                                <td>{{ menu.updateAt ? menu.updateAt|date('Y-m-d H:i:s') : '' }}</td>--}}
                <td>
                    <a href="{{ route('categories.show',$cat->id) }}" class="btn btn-outline-primary" style="width: 80px">show</a>
                    <a href="{{ route('categories.edit',$cat->id) }}" class="btn btn-outline-warning" style="width:80px;">edit</a>
                    @if($cat->deleted_at)
                        <form action="{{ route('categories.restore',$cat->id) }}"

                              method="post">

                            @csrf
                            @method('PUT')
                            <button style="margin-left: 170px;margin-top: -67px;" class="btn btn-outline-success"

                                    type="submit">Restaurer</button>
                        </form>


                        <form action="{{ route('categories.force.destroy',$cat->id) }}"
                              method="post">
                            @csrf
                            @method('DELETE')

                            <button
                                class="btn btn-outline-danger" style="width:200px;margin-top: -114px;margin-left: 267px"
                                type="submit">Supprimer definitivement</button>
                        </form>


                    @else
                        <form action="{{ route('categories.destroy',$cat->id) }}"
                              method="post">
                            @csrf
                            @method('DELETE')

                            <button
                                class="btn btn-outline-danger" style="width:100px;margin-top: -67px;margin-left:170px"
                                type="submit">Supprimer</button>
                        </form>
                @endif
            </tr>
        @endforeach

        </tbody>
    </table>
    <div class="navigation">
        {{ $category->links() }}
    </div>


@endsection

resources/views/category/show.blade.php
@extends('welcome')

@section('content')



<div class="row">

    <div class="col-md-7 my-auto">
        <h3>{{ $category->title }}</h3>
        <p>{{ $category->description }}</p>

        <hr>
        <p>

        </p>
    </div>
</div>
<hr>
@auth()
<div style="text-align: center">
    <a href="{{ route('categories.index') }}"class="btn btn-outline-primary" style="">back to list</a>

    <a href="{{ route('categories.edit', $category->id) }}" class="btn btn-outline-warning" style="">edit</a>

{{--    {{ include('items/_delete_form.html.twig') }}--}}
</div>
@endauth


@endsection